### PR TITLE
Made first sentence more inclusive.

### PR DESCRIPTION
**Pull request by sclayton29**
Slightly modified the first sentence to make it more welcoming to people who aren't from the sciences or engineering. Any thoughts?

### CODE REVIEW

**Comment by laufers** [comment]
I try to make that edit anyway but am sometimes forgetting. I agree. In fact I would even suggest that it might be worth it to file an issue on the original template.  

Fix:
With that, you are missing a 'get' with the 'get more done". 

Thought:
And could we say problems and workflows and not just problems?

**Comment by sclayton29** [comment]
Fixed the missing 'get'. Thanks for pointing that out! 

I like your idea of adding workflows. Now that I'm thinking about it, I'm not sure I like problems at all. Does problems as it is currently written apply to problems(i.e., technical troubleshooting) with research or a research question? 

What if we just said workflows and left out problems? 

I may be completely overthinking this.

**Comment by laufers** [comment]
No, I do not think you are over-thinking. Problems implies a negative and if we are promoting more in less time and having a more positive view then dropping problems and just using workflows is good. 

This does not mean that there are not problems but many times "the problem" is what the research is trying to address and not that there are issues with the workflow.  

Now I am over-thinking.

**Comment by sclayton29** [comment]
I like just using workflows, but let's let this sit for a day to see if anyone else wants to weigh in.

**Comment by bstamps** [comment]
To weigh in from afar- 
I totally agree with the change- any way to encourage inclusion and participation is a good thing!

Also agree that dropping problems and using workflows is more positive/general, and has less of a negative connotation. Even if someone isn't having "a problem" with their research, SWC would let them think about adding workflows to it to make their work more efficient. 

My 2 cents.

**Comment by lo5an** [comment]
I like the direction of this a lot, but I'm wondering about referring to git+bash+python as "basic computing skills". 

Maybe something like one of these would be more :
*  "teaches researchers basic programming, version control, and command line computing" ?
*  "teaches researches the basics of writing and maintaining code"
*  "teaches the basics of using code to control your computer"

Also, +1 to "workflows".

**Comment by sclayton29** [comment]
I those are great ideas, Logan. I'm leaning towards "teaches the basics of writing and maintaining code"

**Comment by laufers** [comment]
Sounds like we are all on-board. I think that this are also worth at least an issue track if not a PR back to SWC. I would be curious to see what the rest of the community thinks.

**Pull request merged**
